services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - redis

  worker:
    build: .
    container_name: celery_worker
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"