# Generated by Django 5.2.4 on 2025-07-08 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.FileField(upload_to='media/')),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_type', models.CharField(max_length=7)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users_To_Docs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=63)),
                ('docs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frapp.docs')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_price', models.FloatField()),
                ('payment', models.BooleanField(default=False)),
                ('docs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frapp.docs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frapp.users_to_docs')),
            ],
        ),
    ]
