# Generated by Django 5.2.4 on 2025-07-08 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='docs_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='frapp.docs'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users_to_docs',
            name='docs_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_to_docs', to='frapp.docs'),
        ),
    ]
