# Generated by Django 5.2.4 on 2025-07-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0002_alter_cart_docs_id_alter_cart_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='file_path',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
